import { Account } from '../types';

export const getStandardAccounts = (companyId: string): Account[] => {
  const accounts: Partial<Account>[] = [
    // Page 1: ACTIVOS
    { codigo: '1', nombre: 'ACTIVO', tipo: 'Activo', imputable: false },
    { codigo: '101', nombre: 'ACTIVO CORRIENTE', tipo: 'Activo', imputable: false },
    { codigo: '10101', nombre: 'EFECTIVO Y EQUIVALENTE', tipo: 'Activo', imputable: false },
    { codigo: '1010101', nombre: 'CAJA', tipo: 'Activo', imputable: true },
    { codigo: '1010102', nombre: 'BANCOS', tipo: 'Activo', imputable: true },
    { codigo: '10102', nombre: 'OTROS ACT. FINANCIEROS CORR.', tipo: 'Activo', imputable: false },
    { codigo: '1010210', nombre: 'DEPOSITO A PLAZO BANCOS', tipo: 'Activo', imputable: true, efectivoPos: '205', efectivoNeg: '206' },
    { codigo: '1010220', nombre: 'FONDOS MUTUOS', tipo: 'Activo', imputable: true, efectivoPos: '205', efectivoNeg: '206' },
    { codigo: '10103', nombre: 'OTROS ACT. NO FINANCIEROS COR.', tipo: 'Activo', imputable: false },
    { codigo: '1010310', nombre: 'UTILES DE OFICINA', tipo: 'Activo', imputable: true, efectivoPos: '130', efectivoNeg: '130' },
    { codigo: '1010320', nombre: 'MATERIALES DE OFICINA', tipo: 'Activo', imputable: true, efectivoPos: '130', efectivoNeg: '130' },
    { codigo: '1010350', nombre: 'ANTICIPOS DE PROVEEDORES', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '1010351', nombre: 'ANTICIPOS PUBLICIDAD', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '1010352', nombre: 'ANTICIPOS DE HONORARIOS', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '1010353', nombre: 'ANTICIPOS DE SUELDOS', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '1010370', nombre: 'PRIMAS DE SEGURO', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '1010380', nombre: 'RENTAS PAGADAS POR ANTICIPADO', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '10104', nombre: 'DEUDORES COMER. Y OTRAS CXC', tipo: 'Activo', imputable: false },
    { codigo: '1010401', nombre: 'CLIENTES', tipo: 'Activo', imputable: true, efectivoPos: '101', efectivoNeg: '101' },
    { codigo: '1010415', nombre: 'HONORARIOS POR COBRAR', tipo: 'Activo', imputable: true, efectivoPos: '101', efectivoNeg: '101' },
    { codigo: '1010420', nombre: 'ESTIMACION DEUDORES INCOBRABLE', tipo: 'Activo', imputable: true },
    { codigo: '1010430', nombre: 'CHEQUES A FECHA', tipo: 'Activo', imputable: true, efectivoPos: '101', efectivoNeg: '101' },
    { codigo: '1010431', nombre: 'LETRAS POR COBRAR', tipo: 'Activo', imputable: true, efectivoPos: '101', efectivoNeg: '101' },
    { codigo: '1010432', nombre: 'PAGARES POR COBRAR', tipo: 'Activo', imputable: true, efectivoPos: '101', efectivoNeg: '101' },
    { codigo: '1010440', nombre: 'OTROS DOCUMENTOS POR COBRAR', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '10105', nombre: 'CXC ENTIDADES REL. CORRIENTES', tipo: 'Activo', imputable: false },
    { codigo: '1010500', nombre: 'MERCADERIAS', tipo: 'Activo', imputable: true },
    { codigo: '1010501', nombre: 'CXC EMP. RELACIONADAS', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '10106', nombre: 'INVENTARIOS', tipo: 'Activo', imputable: false },
    { codigo: '1010610', nombre: 'MATERIAS PRIMAS', tipo: 'Activo', imputable: true, efectivoPos: '120', efectivoNeg: '120' },
    { codigo: '1010611', nombre: 'MATERIALES DIRECTOS', tipo: 'Activo', imputable: true, efectivoPos: '120', efectivoNeg: '120' },
    { codigo: '1010620', nombre: 'PRODUCTOS EN PROCESO', tipo: 'Activo', imputable: true, efectivoPos: '120', efectivoNeg: '120' },
    { codigo: '1010621', nombre: 'PRODUCTOS TERMINADOS', tipo: 'Activo', imputable: true, efectivoPos: '120', efectivoNeg: '120' },
    { codigo: '1010630', nombre: 'MERCADERIAS NACIONALES', tipo: 'Activo', imputable: true, efectivoPos: '120', efectivoNeg: '120' },
    { codigo: '1010640', nombre: 'IMPORTACIONES EN TRANSITO', tipo: 'Activo', imputable: true, efectivoPos: '120', efectivoNeg: '120' },
    { codigo: '1010690', nombre: 'PROVISION MERCADERIA OBSOLETA', tipo: 'Activo', imputable: true, efectivoPos: '120', efectivoNeg: '120' },
    { codigo: '10107', nombre: 'ACTIVOS BIOLOGICOS CORRIENTES', tipo: 'Activo', imputable: false },
    { codigo: '1010701', nombre: 'ACTIVOS BIOLOGICOS CORRIENTES', tipo: 'Activo', imputable: true, efectivoPos: '120', efectivoNeg: '120' },
    { codigo: '10108', nombre: 'ACTIVOS IMPUESTOS CORRIENTES', tipo: 'Activo', imputable: false },
    { codigo: '1010801', nombre: 'PPM', tipo: 'Activo', imputable: true, efectivoPos: '140', efectivoNeg: '140' },
    { codigo: '1010802', nombre: 'IVA CREDITO FISCAL', tipo: 'Activo', imputable: true, efectivoPos: '141', efectivoNeg: '141' },
    { codigo: '1010803', nombre: 'IVA REMANENTE CREDITO FISCAL', tipo: 'Activo', imputable: true, efectivoPos: '141', efectivoNeg: '141' },
    { codigo: '1010804', nombre: 'IMPUESTO ADICIONAL', tipo: 'Activo', imputable: true, efectivoPos: '142', efectivoNeg: '142' },
    { codigo: '1010805', nombre: 'IMPUESTO ESPECIFICO', tipo: 'Activo', imputable: true, efectivoPos: '142', efectivoNeg: '142' },
    { codigo: '1010806', nombre: 'REMANENTE IVA ANTICIPADO', tipo: 'Activo', imputable: true, efectivoPos: '141', efectivoNeg: '141' },
    { codigo: '1010807', nombre: 'IVA ANTICIPADO CARNE O HARINA', tipo: 'Activo', imputable: true, efectivoPos: '141', efectivoNeg: '141' },
    { codigo: '1010825', nombre: 'RETENCION HONORARIO POR COBRAR', tipo: 'Activo', imputable: true, efectivoPos: '142', efectivoNeg: '142' },
    { codigo: '10109', nombre: 'ACTIVOS NO CORR. X CLASIFICAR', tipo: 'Activo', imputable: false },
    { codigo: '1010910', nombre: 'ACTIVO MANT. PARA VENTA', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '1010920', nombre: 'ACTIVO MANT. PARA PROPIETARIOS', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '102', nombre: 'ACTIVO NO CORRIENTE', tipo: 'Activo', imputable: false },
    { codigo: '10201', nombre: 'OTROS ACTIVOS FINAN. NO CORR.', tipo: 'Activo', imputable: false },
    { codigo: '1020101', nombre: 'OTROS FINANCIEROS NO CORR.', tipo: 'Activo', imputable: true, efectivoPos: '205', efectivoNeg: '206' },
    { codigo: '10202', nombre: 'OTROS NO FINANCIEROS NO CORR.', tipo: 'Activo', imputable: false },
    { codigo: '1020201', nombre: 'ARRIENDOS EN GARANTIA POR REC.', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '10203', nombre: 'DERECHOS COBRAR NO CORRIENTES', tipo: 'Activo', imputable: false },
    
    // Page 2
    { codigo: '1020301', nombre: 'DEUDORES A LARGO PLAZO', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '10204', nombre: 'CXC A ENTIDAD REL. NO CORR.', tipo: 'Activo', imputable: false },
    { codigo: '1020410', nombre: 'CXC A EMPRESA RELACIONADA L.P', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '1020420', nombre: 'DXC A EMPRESA RELACIONADA L.P', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '1020430', nombre: 'OTROS DXC A EMP RELACIONADA LP', tipo: 'Activo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '10205', nombre: 'INV. CONTAB. METODO PARTIC', tipo: 'Activo', imputable: false },
    { codigo: '1020501', nombre: 'INV. CONTAB. METODO PARTIC', tipo: 'Activo', imputable: true },
    { codigo: '10206', nombre: 'ACTIVOS INTANGIBLES NO PLUSV.', tipo: 'Activo', imputable: false },
    { codigo: '1020601', nombre: 'DERECHOS DE AUTOR', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '1020602', nombre: 'MARCA REGISTRADA', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '1020603', nombre: 'PATENTES', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '1020604', nombre: 'SOFTWARE', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '1020605', nombre: 'FRANQUICIAS', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '1020606', nombre: 'GASTOS DE CONSTITUCION', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '10207', nombre: 'PLUSVALIA', tipo: 'Activo', imputable: false },
    { codigo: '1020701', nombre: 'PLUSVALIA', tipo: 'Activo', imputable: true },
    { codigo: '10208', nombre: 'PROPIEDAD PLANTA Y EQUIPO', tipo: 'Activo', imputable: false },
    { codigo: '1020810', nombre: 'MAQUINARIAS Y EQUIPOS', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '1020811', nombre: 'DEP ACUM MAQUINARIAS Y EQUIPOS', tipo: 'Activo', imputable: true },
    { codigo: '1020820', nombre: 'MUEBLES Y UTILES', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '1020821', nombre: 'DEPR ACUM MUEBLES Y UTILES', tipo: 'Activo', imputable: true },
    { codigo: '1020824', nombre: 'EQUIPOS COMPUTACIONALES', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '1020825', nombre: 'DEP ACUM EQUIPOS COMPUTACIONAL', tipo: 'Activo', imputable: true },
    { codigo: '1020830', nombre: 'INSTALACIONES', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '1020831', nombre: 'DEPR ACUM INSTALACIONES', tipo: 'Activo', imputable: true },
    { codigo: '10209', nombre: 'ACTIVOS BIOLOGICOS NO CORR.', tipo: 'Activo', imputable: false },
    { codigo: '1020901', nombre: 'ACTIVOS BIOLOGICOS NO CORR.', tipo: 'Activo', imputable: true, efectivoPos: '201', efectivoNeg: '202' },
    { codigo: '10210', nombre: 'PROPIEDAD DE INVERSION', tipo: 'Activo', imputable: false },
    { codigo: '1021001', nombre: 'PROPIEDAD DE INVERSION', tipo: 'Activo', imputable: true, efectivoPos: '205', efectivoNeg: '206' },
    { codigo: '10211', nombre: 'ACTIVOS POR IMPUESTOS DIFERIDO', tipo: 'Activo', imputable: false },
    { codigo: '1021101', nombre: 'ACTIVOS POR IMPUESTOS DIFERIDO', tipo: 'Activo', imputable: true, efectivoPos: '142', efectivoNeg: '142' },

    { codigo: '2', nombre: 'PASIVO Y PATRIMONIO', tipo: 'Pasivo', imputable: false },
    { codigo: '201', nombre: 'PASIVO CORRIENTE', tipo: 'Pasivo', imputable: false },
    { codigo: '20101', nombre: 'OTROS PASIVOS FINAN. CORR.', tipo: 'Pasivo', imputable: false },
    { codigo: '2010101', nombre: 'DEUDAS CON BANCOS CORTO PLAZO', tipo: 'Pasivo', imputable: true, efectivoPos: '420', efectivoNeg: '431' },
    { codigo: '2010102', nombre: 'LINEA DE CREDITO BANCOS', tipo: 'Pasivo', imputable: true, efectivoPos: '420', efectivoNeg: '431' },
    { codigo: '2010120', nombre: 'ACREEDORES POR LEASING', tipo: 'Pasivo', imputable: true, efectivoPos: '420', efectivoNeg: '431' },
    { codigo: '2010130', nombre: 'OBLIGACIONES POR FACTORING', tipo: 'Pasivo', imputable: true, efectivoPos: '420', efectivoNeg: '431' },
    { codigo: '20102', nombre: 'CXP COMERCIALES Y OTRAS CTAS', tipo: 'Pasivo', imputable: false },
    { codigo: '2010201', nombre: 'PROVEEDORES', tipo: 'Pasivo', imputable: true, efectivoPos: '120', efectivoNeg: '120' },
    { codigo: '2010210', nombre: 'CUENTAS POR PAGAR', tipo: 'Pasivo', imputable: true, efectivoPos: '420', efectivoNeg: '431' },
    { codigo: '2010215', nombre: 'SUELDOS POR PAGAR', tipo: 'Pasivo', imputable: true, efectivoPos: '130', efectivoNeg: '130' },
    { codigo: '2010220', nombre: 'HONORARIOS POR PAGAR', tipo: 'Pasivo', imputable: true, efectivoPos: '130', efectivoNeg: '130' },
    { codigo: '2010225', nombre: 'IMPOSIONES POR PAGAR', tipo: 'Pasivo', imputable: true, efectivoPos: '150', efectivoNeg: '150' },
    { codigo: '20104', nombre: 'CXP ENTIDAD RELACIONADA CORR.', tipo: 'Pasivo', imputable: false },
    { codigo: '2010401', nombre: 'CXP ENTIDAD RELACIONADA CORR.', tipo: 'Pasivo', imputable: true, efectivoPos: '420', efectivoNeg: '431' },
    { codigo: '20105', nombre: 'OTRAS PROVISIONES A C.P.', tipo: 'Pasivo', imputable: false },
    { codigo: '2010590', nombre: 'PROVISIONES VARIAS', tipo: 'Pasivo', imputable: true },
    { codigo: '20109', nombre: 'PASIVOS POR IMPUESTOS CORR.', tipo: 'Pasivo', imputable: false },
    { codigo: '2010910', nombre: 'IMPUESTO UNICO TRABAJADORES', tipo: 'Pasivo', imputable: true, efectivoPos: '142', efectivoNeg: '142' },
    { codigo: '2010915', nombre: 'PRESTAMO SOLIDARIO TRABAJADOR', tipo: 'Pasivo', imputable: true, efectivoPos: '142', efectivoNeg: '142' },
    { codigo: '2010920', nombre: 'IVA DEBITO FISCAL', tipo: 'Pasivo', imputable: true, efectivoPos: '141', efectivoNeg: '141' },
    { codigo: '2010925', nombre: 'OTROS IMPUESTOS', tipo: 'Pasivo', imputable: true, efectivoPos: '142', efectivoNeg: '142' },
    { codigo: '2010930', nombre: 'RETENCION IMPUESTO HONORARIOS', tipo: 'Pasivo', imputable: true, efectivoPos: '142', efectivoNeg: '142' },

    // Page 3
    { codigo: '2010940', nombre: 'RETENCION INGRESO HONORARIO', tipo: 'Pasivo', imputable: true, efectivoPos: '142', efectivoNeg: '142' },
    { codigo: '2010950', nombre: 'IVA POR PAGAR', tipo: 'Pasivo', imputable: true },
    { codigo: '2010990', nombre: 'PROVISION IMPUESTO A LA RENTA', tipo: 'Pasivo', imputable: true, efectivoPos: '140', efectivoNeg: '140' },
    { codigo: '20110', nombre: 'PASIVOS CORR. BEN. EMPLEADOS', tipo: 'Pasivo', imputable: false },
    { codigo: '2011001', nombre: 'PROVISION VACACIONES PERSONAL', tipo: 'Pasivo', imputable: true, efectivoPos: '150', efectivoNeg: '150' },
    { codigo: '20111', nombre: 'OTROS PASIVOS NO FINANC. CORR.', tipo: 'Pasivo', imputable: false },
    { codigo: '2011101', nombre: 'INGRESOS PERCIBIDOS ADELANTADO', tipo: 'Pasivo', imputable: true, efectivoPos: '101', efectivoNeg: '101' },
    { codigo: '2011120', nombre: 'ARRIENDOS RECIBIDOS GARANTIA', tipo: 'Pasivo', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '202', nombre: 'PASIVO NO CORRIENTE', tipo: 'Pasivo', imputable: false },
    { codigo: '20201', nombre: 'OTROS PASIVOS FINAN. NO CORR.', tipo: 'Pasivo', imputable: false },
    { codigo: '2020101', nombre: 'DEUDAS CON BANCOS LARGO PLAZO', tipo: 'Pasivo', imputable: true, efectivoPos: '420', efectivoNeg: '431' },
    { codigo: '20202', nombre: 'PASIVOS NO CORRIENTES', tipo: 'Pasivo', imputable: false },
    { codigo: '2020201', nombre: 'ACREEDORES LEASING A L.P.', tipo: 'Pasivo', imputable: true, efectivoPos: '420', efectivoNeg: '431' },
    { codigo: '20203', nombre: 'CXP ENTIDAD RELAC. NO CORR.', tipo: 'Pasivo', imputable: false },
    { codigo: '2020301', nombre: 'CXP EMP. RELACIONADAS L.P.', tipo: 'Pasivo', imputable: true, efectivoPos: '420', efectivoNeg: '431' },
    { codigo: '2020302', nombre: 'CXP SOCIOS A L.P.', tipo: 'Pasivo', imputable: true, efectivoPos: '420', efectivoNeg: '431' },
    { codigo: '20204', nombre: 'OTRAS PROVISIONES A L.P.', tipo: 'Pasivo', imputable: false },
    { codigo: '20205', nombre: 'PASIVOS IMPUESTOS DIFERIDOS', tipo: 'Pasivo', imputable: true },
    { codigo: '20206', nombre: 'PROVISIONES NO CORR. BEN. EMP.', tipo: 'Pasivo', imputable: false },
    { codigo: '2020601', nombre: 'PROVISION INDEM. AÑOS SERVICIO', tipo: 'Pasivo', imputable: true, efectivoPos: '150', efectivoNeg: '150' },
    { codigo: '20207', nombre: 'OTROS PASIVOS NO FINAN NO CORR', tipo: 'Pasivo', imputable: true },

    { codigo: '3', nombre: 'PATRIMONIO', tipo: 'Pasivo', imputable: false },
    { codigo: '301', nombre: 'CAPITAL EMITIDO', tipo: 'Pasivo', imputable: false },
    { codigo: '30101', nombre: 'CAPITAL SOCIAL', tipo: 'Pasivo', imputable: true, efectivoPos: '401', efectivoNeg: '401' },
    { codigo: '30102', nombre: 'CAPITAL PREFERENTE', tipo: 'Pasivo', imputable: true, efectivoPos: '401', efectivoNeg: '401' },
    { codigo: '302', nombre: 'GANANCIAS ACUMULADAS', tipo: 'Pasivo', imputable: false },
    { codigo: '30201', nombre: 'PERDIDAS ACUMULADAS', tipo: 'Pasivo', imputable: true },
    { codigo: '30202', nombre: 'UTILIDADES ACUMULADAS', tipo: 'Pasivo', imputable: true },
    { codigo: '30203', nombre: 'PERDIDAS Y GANANCIAS EJERCICIO', tipo: 'Pasivo', imputable: true },
    { codigo: '303', nombre: 'CUENTAS CORRIENTES DE SOCIOS', tipo: 'Pasivo', imputable: false },
    { codigo: '30301', nombre: 'CTA CTE SOCIO 1', tipo: 'Pasivo', imputable: true, efectivoPos: '401', efectivoNeg: '440' },
    { codigo: '30302', nombre: 'CTA CTE SOCIO 2', tipo: 'Pasivo', imputable: true, efectivoPos: '401', efectivoNeg: '440' },
    { codigo: '304', nombre: 'ACCIONES PROPIAS EN CARTERA', tipo: 'Pasivo', imputable: true },
    { codigo: '305', nombre: 'OTRAS PARTICIP. PATRIMONIO', tipo: 'Pasivo', imputable: true },
    { codigo: '306', nombre: 'OTRAS RESERVAS', tipo: 'Pasivo', imputable: false },
    { codigo: '30601', nombre: 'REVALORIZACION CAPITAL PROPIO', tipo: 'Pasivo', imputable: true },
    { codigo: '307', nombre: 'PATRIMONIO DUEÑOS CONTROLADORA', tipo: 'Pasivo', imputable: true },
    { codigo: '308', nombre: 'PARTICIPACIONES NO CONTROLADOR', tipo: 'Pasivo', imputable: true },

    { codigo: '4', nombre: 'RESULTADOS', tipo: 'Pérdida', imputable: false },
    { codigo: '401', nombre: 'ESTADO DE RESULTADOS', tipo: 'Pérdida', imputable: false },
    { codigo: '40101', nombre: 'INGRESOS ACTIVIDAD ORDINARIAS', tipo: 'Ganancia', imputable: false },
    { codigo: '4010110', nombre: 'VENTAS Y SERVICIOS AFECTOS', tipo: 'Ganancia', imputable: true, efectivoPos: '101', efectivoNeg: '101' },
    { codigo: '4010120', nombre: 'VENTAS Y SERVICIOS EXENTOS', tipo: 'Ganancia', imputable: true, efectivoPos: '101', efectivoNeg: '101' },
    { codigo: '4010130', nombre: 'EXPORTACIONES', tipo: 'Ganancia', imputable: true, efectivoPos: '101', efectivoNeg: '101' },
    { codigo: '40102', nombre: 'COSTO DE VENTAS', tipo: 'Pérdida', imputable: false },
    { codigo: '4010210', nombre: 'COSTO VENTAS AFECTAS', tipo: 'Pérdida', imputable: true },
    { codigo: '4010220', nombre: 'COSTO VENTAS EXENTAS', tipo: 'Pérdida', imputable: true },
    { codigo: '4010230', nombre: 'COSTO EXPORTACIONES', tipo: 'Pérdida', imputable: true },
    { codigo: '4010250', nombre: 'COSTOS DE COMISION EN VENTAS', tipo: 'Pérdida', imputable: true },
    { codigo: '40105', nombre: 'UTILIDAD BRUTA', tipo: 'Ganancia', imputable: false },
    { codigo: '40106', nombre: 'OTROS INGRESOS, POR FUNCION', tipo: 'Ganancia', imputable: false },
    { codigo: '4010601', nombre: 'OTROS INGRESOS, POR FUNCION', tipo: 'Ganancia', imputable: true, efectivoPos: '101', efectivoNeg: '101' },

    // Page 4
    { codigo: '40107', nombre: 'COSTOS DE DISTRIBUCION', tipo: 'Pérdida', imputable: false },
    { codigo: '4010701', nombre: 'MOVILIZACION', tipo: 'Pérdida', imputable: true, efectivoPos: '130', efectivoNeg: '130' },
    { codigo: '40108', nombre: 'GASTOS DE ADMINISTRACION', tipo: 'Pérdida', imputable: false },
    { codigo: '4010810', nombre: 'GASTOS DE SUELDOS Y SALARIOS', tipo: 'Pérdida', imputable: true, efectivoPos: '130', efectivoNeg: '130' },
    { codigo: '4010812', nombre: 'GASTOS DE FONASA E ISAPRE', tipo: 'Pérdida', imputable: true, efectivoPos: '150', efectivoNeg: '150' },
    { codigo: '4010813', nombre: 'GASTOS DE AFC EMPLEADOR', tipo: 'Pérdida', imputable: true, efectivoPos: '150', efectivoNeg: '150' },
    { codigo: '4010814', nombre: 'GASTOS DE SEGURO DE INVALIDEZ', tipo: 'Pérdida', imputable: true, efectivoPos: '150', efectivoNeg: '150' },
    { codigo: '4010815', nombre: 'GASTOS DE SEGURO ACCIDENTE', tipo: 'Pérdida', imputable: true, efectivoPos: '150', efectivoNeg: '150' },
    { codigo: '4010816', nombre: 'GASTOS DE MOVILIZACION', tipo: 'Pérdida', imputable: true, efectivoPos: '150', efectivoNeg: '150' },
    { codigo: '4010817', nombre: 'GASTOS DE COLACION', tipo: 'Pérdida', imputable: true, efectivoPos: '150', efectivoNeg: '150' },
    { codigo: '4010818', nombre: 'BONOS Y OTROS', tipo: 'Pérdida', imputable: true, efectivoPos: '150', efectivoNeg: '150' },
    { codigo: '4010822', nombre: 'HONORARIOS', tipo: 'Pérdida', imputable: true, efectivoPos: '130', efectivoNeg: '130' },
    { codigo: '4010890', nombre: 'GASTOS GENERALES', tipo: 'Pérdida', imputable: true, efectivoPos: '130', efectivoNeg: '130' },
    { codigo: '40109', nombre: 'OTROS GASTOS, POR FUNCION', tipo: 'Pérdida', imputable: false },
    { codigo: '4010916', nombre: 'OTROS GASTOS, POR FUNCION', tipo: 'Pérdida', imputable: true, efectivoPos: '130', efectivoNeg: '130' },
    { codigo: '40110', nombre: 'OTRAS GANANCIAS (PERDIDAS)', tipo: 'Ganancia', imputable: false },
    { codigo: '4011010', nombre: 'OTRAS GANANCIAS', tipo: 'Ganancia', imputable: true, efectivoPos: '101', efectivoNeg: '101' },
    { codigo: '4011020', nombre: 'OTRAS PERDIDAS', tipo: 'Pérdida', imputable: true, efectivoPos: '130', efectivoNeg: '130' },
    { codigo: '40120', nombre: 'GANANCIAS (PERDIDAS) ACT. OP.', tipo: 'Ganancia', imputable: false },
    { codigo: '40121', nombre: 'INGRESOS FINANCIEROS', tipo: 'Ganancia', imputable: false },
    { codigo: '4012110', nombre: 'INTERESES GANADOS', tipo: 'Ganancia', imputable: true, efectivoPos: '210', efectivoNeg: '211' },
    { codigo: '40122', nombre: 'COSTOS FINANCIEROS', tipo: 'Pérdida', imputable: false },
    { codigo: '4012210', nombre: 'COSTOS FINANCIEROS', tipo: 'Pérdida', imputable: true, efectivoPos: '430', efectivoNeg: '430' },
    { codigo: '40124', nombre: 'DIFERENCIAS DE CAMBIO', tipo: 'Pérdida', imputable: false },
    { codigo: '4012410', nombre: 'DIFERENCIAS DE CAMBIO', tipo: 'Pérdida', imputable: true },
    { codigo: '40125', nombre: 'RESULTADOS UNIDADES REAJUSTE', tipo: 'Pérdida', imputable: false },
    { codigo: '4012501', nombre: 'REAJUSTE CREDITO IVA Y PPM', tipo: 'Pérdida', imputable: true },
    { codigo: '4012570', nombre: 'REAJUSTE ACTIVOS EN UF', tipo: 'Pérdida', imputable: true },
    { codigo: '4012590', nombre: 'REAJUSTE PASIVOS EN UF', tipo: 'Pérdida', imputable: true },
    { codigo: '40190', nombre: 'GANANCIAS (PERDIDAS) ANTES IMP', tipo: 'Ganancia', imputable: false },
    { codigo: '40191', nombre: 'GASTO POR IMPUESTO GANANCIAS', tipo: 'Pérdida', imputable: false },
    { codigo: '4019101', nombre: 'IMPUESTO A LA RENTA', tipo: 'Pérdida', imputable: true, efectivoPos: '140', efectivoNeg: '140' },
    { codigo: '40192', nombre: 'GANANCIAS (PERDIDAS) OP. CONT.', tipo: 'Ganancia', imputable: false },
    { codigo: '40193', nombre: 'GANANCIA OPE. DISCONTINUADAS', tipo: 'Ganancia', imputable: false },
    { codigo: '4019310', nombre: 'GANANCIAS OPE. DISCONTINUADAS', tipo: 'Ganancia', imputable: true },
    { codigo: '4019320', nombre: 'PERDIDAS OPE. DISCONTINUADA', tipo: 'Pérdida', imputable: true },
    { codigo: '40199', nombre: 'UTILIDAD CONSOLIDADA', tipo: 'Ganancia', imputable: false },
  ];

  return accounts.map((a) => {
    const codigo = a.codigo || '0';
    return {
      ...a,
      id: `std-${companyId}-${codigo}`,
      companyId,
      parentId: null,
      nivel: codigo.length <= 1 ? 1 : codigo.length <= 3 ? 2 : codigo.length <= 5 ? 3 : 4,
      analisis: false,
      conciliacion: false,
      centroCosto: false,
      codigo,
      nombre: a.nombre || 'SIN NOMBRE',
      imputable: a.imputable ?? true,
      tipo: a.tipo || 'Activo'
    } as Account;
  });
};
